<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Restful\Controller\RestfulController' => __DIR__ . '/src/Restful/Controller/RestfulController.php',
    'Restful\Controller\ClientController'  => __DIR__ . '/src/Restful/Controller/ClientController.php',
    'Restful\Module'                       => __DIR__ . '/Module.php',
);