<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Restful\Controller\SampleRestfulController' => __DIR__ . '/src/Restful/Controller/SampleRestfulController.php',
    'Restful\Controller\SampleClientController'  => __DIR__ . '/src/Restful/Controller/SampleClientController.php',
    'Restful\Module'                             => __DIR__ . '/Module.php',
);